###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 0
### date: 19/05/2025
###  
###  ___
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
if (!requireNamespace("tibble", quietly = TRUE)) {  install.packages("tibble") }
if (!requireNamespace("gtsummary", quietly = TRUE)) {  install.packages("gtsummary") }
if (!requireNamespace("plotly", quietly = TRUE)) {  install.packages("plotly") }
if (!requireNamespace("dplyr", quietly = TRUE)) {  install.packages("dplyr") }

if (!requireNamespace("webshot", quietly = TRUE)) {  install.packages("webshot") }
if (!requireNamespace("htmlwidgets", quietly = TRUE)) {  install.packages("htmlwidgets") }
webshot::install_phantomjs()  # Install PhantomJS for webshot

library(tibble)
library(gtsummary)
library(plotly)
library(dplyr)
library(webshot)
library(htmlwidgets)
```

# Get data
```{r load data, include false}
df <- tibble(
  age       = c(32, 30, 32, 29, 24, 38, 25, 24, 48, 29, 22, 29, 24, 28, 24, 25, 
                25, 22, 25, 24, 25, 24, 23, 24, 31, 24, 29, 24, 22, 23, 26, 23, 
                24, 25, 24, 33, 27, 25, 26, 26, 26, 26, 26, 27, 24, 43, 25, 24, 
                27, 28, 29, 24, 26, 28, 25, 24, 26, 24, 26, 31, 24, 26, 31, 34, 
                26, 25, 27, NA),
  age_group = c(2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 
                1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 
                2, 1, 1, 1, NA),
  gender    = c(2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 
                1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 
                1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 
                1, 1, 2, 1, NA),
  ht_in     = c(70, 63, 62, 67, 67, 58, 64, 69, 65, 68, 63, 68, 69, 66, 67, 65, 
                64, 75, 67, 63, 60, 67, 64, 73, 62, 69, 67, 62, 68, 66, 66, 62, 
                64, 68, NA, 68, 70, 68, 68, 66, 71, 61, 62, 64, 64, 63, 67, 66, 
                69, 76, NA, 63, 64, 65, 65, 71, 66, 65, 65, 71, 64, 71, 60, 62, 
                61, 69, 66, NA),
  wt_lbs    = c(216, 106, 145, 195, 143, 125, 138, 140, 158, 167, 145, 297, 146, 
                125, 111, 125, 130, 182, 170, 121, 98, 150, 132, 250, 137, 124, 
                186, 148, 134, 155, 122, 142, 110, 132, 188, 176, 188, 166, 136, 
                147, 178, 125, 102, 140, 139, 60, 147, 147, 141, 232, 186, 212, 
                110, 110, 115, 154, 140, 150, 130, NA, 171, 156, 92, 122, 102, 
                163, 141, NA),
  bmi       = c(30.99, 18.78, 26.52, 30.54, 22.39, 26.12, 23.69, 20.67, 26.29, 
                25.39, 25.68, 45.15, 21.56, 20.17, 17.38, 20.8, 22.31, 22.75, 
                26.62, 21.43, 19.14, 23.49, 22.66, 32.98, 25.05, 18.31, 29.13, 
                27.07, 20.37, 25.01, 19.69, 25.97, 18.88, 20.07, NA, 26.76, 
                26.97, 25.24, 20.68, 23.72, 24.82, 23.62, 18.65, 24.03, 23.86, 
                10.63, 23.02, 23.72, 20.82, 28.24, NA, 37.55, 18.88, 18.3, 
                19.13, 21.48, 22.59, 24.96, 21.63, NA, 29.35, 21.76, 17.97, 
                22.31, 19.27, 24.07, 22.76, NA),
  bmi_3cat  = c(3, 1, 2, 3, 1, 2, 1, 1, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1, 2, 1, 1, 
                1, 1, 3, 2, 1, 2, 2, 1, 2, 1, 2, 1, 1, NA, 2, 2, 2, 1, 1, 1, 1, 
                1, 1, 1, 1, 1, 1, 1, 2, NA, 3, 1, 1, 1, 1, 1, 1, 1, NA, 2, 1, 
                1, 1, 1, 1, 1, NA)
)
df$gender <- factor(df$gender, levels = c(1, 2), labels = c("M", "F"))
```

# Show summary statistics
```{r load data, include false}
tbl_summary <- df %>%select(age, ht_in, wt_lbs, bmi, gender) %>%
  tbl_summary(
    by = gender,
    statistic = list(
      all_continuous() ~ "{mean} ({sd})",
      all_continuous() ~ "{median} ({p25}, {p75})"
    ),
    digits = all_continuous() ~ 1,
    missing = "ifany",
    label = list(
      age ~ "Age (years)",
      ht_in ~ "Height (inches)",
      wt_lbs ~ "Weight (pounds)",
      bmi ~ "BMI"
    )
  ) %>%
  add_n() %>%
  modify_header(label ~ "**Variable**") %>%
  bold_labels()
# Print the summary table
print(tbl_summary)
```

# Show box plot
```{r plot, include false}
# Define:
point_size <- 10
point_color <- 'blue'
point_opacity <- 0.4
line_color <- 'red'
line_width <- 5

font_type <- "Calibri, Arial"
font_size <- 16

graph_title <- 'Age, Height, Weight, BMI'
graph_subtitle <- 'Box plot'
graph_title <- paste0("<b>", graph_title , "</b><br><sup>", graph_subtitle , "")
plot_bkgd_color <- "#f1eece"

x_axis_label <- "Height"
y_axis_label <- "Weight"
x_unit_height <- "in"
y_unit_weight <- "lb"
xaxis_title <- paste0("<b>", x_axis_label , "</b><br><sup>", x_unit_height)
yaxis_title <- paste0("<b>",y_axis_label , "</b><br><sup>", y_unit_weight)
axis_color <- '#a0a0a0'
axis_width <- 2

#do the plot
variables <- c("age", "ht_in", "wt_lbs", "bmi")
titles <- c("Age", "Height", "Weight", "BMI")
units <- c("years", "inches", "pounds", "")

plots <- lapply(seq_along(variables), function(i) {
  var <- variables[i]
  plot_ly(data = df, 
          y = ~get(var), 
          x = ~gender, 
          type = "box", 
          boxpoints = "all",  # Show all points
          jitter = 0.6,       # Add jitter to points
          pointpos = 0,    # Position points to the left of the box
          color = ~gender,    # Color by gender
          colors = c("#1f77b4", "#ff7f0e"),  # Blue for Male, Orange for Female
          marker = list(size = 3, opacity = 0.4, color = "black"),  # Smaller points, lower opacity
          legendgroup = ~gender,  # Group legend by gender
          showlegend = (i == 1)
          ) %>%  # Show legend only for the first plot
    layout(
      title = list(text = titles[i], y = 0.97, font = list(size = font_size, family = font_type)),
      yaxis = list(
        title = paste("<b>", titles[i], ifelse(units[i] != "", paste0("</b><br><sup>", units[i], ""), "")),
        titlefont = list(size = font_size, family = font_type),
        showgrid = FALSE,  # Show y-axis grid lines
        gridcolor = "lightgray",  # Light gray grid lines
        showticklabels = TRUE,  # Hide y-axis tick labels
        tickmode = "auto",
        ticks = "outside",  # Remove y-axis tick marks
        showline = TRUE,  # Hide y-axis line
        linecolor = axis_color,
        linewidth = axis_width,
        ticklen = axis_width*2,
        tickwidth = axis_width,
        tickcolor = axis_color
      ),
      xaxis = list(
        title = ifelse(i %in% c(3, 4), "Gender", ""), 
        titlefont = list(size = font_size, family = font_type),
        showgrid = FALSE,  # Show x-axis grid lines
        gridcolor = "lightgray",  # Light gray grid lines
        showticklabels = TRUE,  # Hide x-axis tick labels
        tickmode = "auto",
        ticks = "",  # Remove x-axis tick marks
        showline = FALSE  # Hide x-axis line,
      ),
      #boxgap = 0.2,         # Reduce the gap between boxes (default is 0.3)
      #boxgroupgap = 0.5,
      margin = list(l = 1, r = 10, t = 50) #Reduced margins to maximize subplot size
    )
})

# Combine plots into a subplot with minimal spacing
subplot(plots, nrows = 2, shareX = TRUE, titleY = TRUE, margin = 0.05) %>%
  layout(
    title = list(text = graph_title, y = 0.95, font = list(size = font_size*1.3, family = font_type),
      x = 0.4,
      xref = "paper",
      xanchor = "center"),
    showlegend = TRUE,
    margin = list(l = 1, r = 10, t = 50)  # Minimal global margins
  )
```






# Linear regression model
```{r do_regression, include false}
model <- lm(ydata ~ xdata, data = df)

# Create regression table using gtsummary
regression_table <- tbl_regression(model, intercept = TRUE, conf.int = TRUE) %>%
  add_global_p() %>%
  bold_labels() %>%
  add_significance_stars(hide_p=FALSE, hide_se=FALSE,hide_ci=FALSE) %>%      # Add significance stars
  add_glance_table(label = list(sigma = "\U03C3"),
                  include = c(r.squared, AIC, p.value)) %>%      # Add significance stars
  add_glance_source_note(label = list(df  ~ "Degrees of Freedom", sigma = "\U03C3"),
                                include = c(df , sigma, statistic, logLik))   # Add model fit statistics (e.g., R², AIC, BIC)
  modify_column_unhide(columns = "std.error") %>%  # Unhide std.error column
  as_kable(regression_table)

# Print regression table
print(regression_table)
```

# Create plot
```{r plot, include false}
# Define:
point_size <- 10
point_color <- 'blue'
point_opacity <- 0.4
line_color <- 'red'
line_width <- 5

font_type <- "Calibri, Arial"
font_size <- 18

graph_title <- 'Height vs Weight'
graph_subtitle <- 'Linear Regression'
graph_title <- paste0("<b>", graph_title , "</b><br><sup>", graph_subtitle , "")
plot_bkgd_color <- "#f1eece"

x_axis_label <- "Height"
y_axis_label <- "Weight"
x_unit_height <- "in"
y_unit_weight <- "lb"
xaxis_title <- paste0("<b>", x_axis_label , "</b><br><sup>", x_unit_height)
yaxis_title <- paste0("<b>",y_axis_label , "</b><br><sup>", y_unit_weight)
axis_color <- 'slategray'
axis_width <- 2

#remove NA values from the data frame
#df_plotly <- df %>% filter(!is.na(xdata) & !is.na(ydata))
df_plotly <- df
# Create the plot using plotly

fig1 <- plot_ly(data = df_plotly, x = ~xdata, y = ~ydata,
             type = 'scatter', mode = 'markers',
             marker = list(size = point_size, color = point_color, opacity = point_opacity,
             line = list(color='white', width=0.5)),
             name = "data") %>%
  add_lines(x = df_plotly$xdata, y = predict(model, newdata = df),
            line = list(color = line_color, width = line_width),
            mode = 'lines',
            marker = NULL,
            name= " model") %>%
  layout(title = list(text = graph_title,
                     font = list(family = font_type, size = font_size*1.3),
                     xref = "paper",  # Center title over plot
                     x = 0.5,  # Center horizontally
                     xanchor = "center"),
         xaxis = list(title = list(text = xaxis_title,
                                  font = list(family = font_type)
                                  #automargin = false
                                  ),
                      linecolor = axis_color,
                      linewidth = axis_width,
                      ticks = "outside",
                      tickcolor = axis_color,
                      ticklen = axis_width*2,
                      tickwidth = axis_width),
         yaxis = list(title = list(text = yaxis_title,
                                  font = list(family = font_type)
                                  #automargin = TRUE
                                  ),
                      linecolor = axis_color,
                      linewidth = axis_width,
                      ticks = "outside",
                      tickcolor = axis_color,
                      ticklen = axis_width*2,
                      tickwidth = axis_width),
         font = list(family = font_type, size = font_size),
         plot_bgcolor = plot_bkgd_color,  # Light blue background
         margin = list(l=95, r=5, t=60, b=40,pad=0),  # Adjust top margin to align with x-axis label
         legend = list(font = list(size = font_size*0.6), itemwidth = 10),  # Smaller legend font
         showlegend = TRUE)  # Show legend with trace labels

# Display plot
fig1

```