###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 1
### date: 19/05/2025
###  
###  כאן נראה איך להטעין נתונים מטבלה וליצור גרף
###

# Reset memorט
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}


# List of packages to install and load
library(plotly)
```

# Get data ftom table
```{r load data, include false}
data <- read.table( header=TRUE, sep=",",
                        text="source,year,value
    S1,1976,56.98
    S1,1977,55.26
    S1,1978,68.83
    S1,1979,59.70
    S1,1980,57.58
    S1,1981,61.54
    S1,1982,48.65
    S1,1983,53.45
    S1,1984,45.95
    S1,1985,51.95
    S1,1986,51.85
    S1,1987,54.55
    S1,1988,51.61
    S1,1989,52.24
    S1,1990,49.28
    S1,1991,57.33
    S1,1992,51.28
    S1,1993,55.07
    S1,1994,50.88
    S2,1993,54.90
    S2,1994,51.20
    S2,1995,52.10
    S2,1996,51.40
    S3,2002,57.95
    S3,2003,47.95
    S3,2004,48.15
    S3,2005,37.80
    S3,2006,56.96
    S3,2007,48.91
    S3,2008,44.00
    S3,2009,45.35
    S3,2010,49.40
    S3,2011,51.19")
cutoff <- data.frame( x = c(-Inf, Inf), y = 50, cutoff = factor(50) )
```

# Show graph using ggplot and ggplotly (both inside ploly)
```{r load data, include false}
ggplot(data, aes( year, value ) ) +
    geom_point(aes( colour = source )) +
    geom_smooth(aes( group = 1 )) +
    geom_hline(yintercept = 50)

ggplotly()
``` 