###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 2
### date: 19/05/2025
###  
###  כאן נלמד לטפל בנתונים
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
library(tidyverse)
library(kableExtra)
library(tibble)
library(readxl)
library(lubridate)
library(plotly)
```

# Get data
```{r load data, include false}
path <- "./Data/stroke_data.csv"
stroke <- read.csv(path)

path <- "./Data/peptic_ulcer.xlsx"
pep <- read_excel(path)
```

# Check out the variables
```{r load data, include false}
glimpse(stroke)
print(stroke, n=20)


kable_table_stroke <- stroke %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Stroke data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_stroke)


glimpse(pep)
print(pep, n=20)

kable_table_pep <- pep %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_pep)
```

# Create new dataframe with only a few viariables
```{r cases, include false}
# This take the ten variables we want and put them is a new dataframe
pep2 <- pep %>% 
  dplyr::select(age, systolic, diastolic, perforation, twc,
                              gender, vomiting, malena, ASA, outcome)

kable_table_pep2 <- pep2 %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer smaller data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_pep2)



```


# Create a new variable using data in the dataframe
```{r incidence, include false}
# We will take systoilic and diastolic and create a new variable
# pulsepressure and add it to the end of the dataframe
# pulsepressure = systolic - diastolic
pep2 <- pep2 %>% 
  mutate(pulse_pressure = systolic - diastolic)
pep2 %>% 
  dplyr::select(systolic, diastolic, pulse_pressure ) %>% 

kable_table_pep2 <- pep2 %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer smaller data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_pep2)
```

# Convert variables to date using mutuate(dmy()) lubrifate function
```{r pop, include false}
# Create the plot
stroke <- stroke %>% 
  mutate(doa = dmy(doa), dod = dmy(dod))   # this is a lubridate function
stroke

kable_table_stroke <- stroke %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Stroke data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_stroke)
```

# Rename variables
```{r pop, include false}
# Sometime we want to give variables "better" names
# just make sure there are no spaces in the new name"
# Also not sure if this works in Hebrew.
pep2 <- pep2 %>% 
  rename(sex = gender, asa = ASA)  # note: the original names were "gender" and "ASA"

kable_table_pep2 <- pep2 %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer smaller data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_pep2)
```