###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 3
### date: 19/05/2025
###  
###  סטטיסטיקה תאורית
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
library(gtsummary)
library(tidyverse)
library(kableExtra)
library(tibble)
library(patchwork)
library(here)
library(readxl)
```

# Get data
```{r load data, include false}
path <- "./Data/peptic_ulcer.xlsx"
pep <- read_excel(path)
```

# Check out the variables
```{r load data, include false}
glimpse(pep)
print(pep, n=20)

kable_table_pep <- pep %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")
print(kable_table_pep)
```

# use only a few variables
```{r sort_data, include false}
# This take the ten variables we want and put them is a new dataframe
pep <- pep %>% 
  select(age, systolic, diastolic, hemoglobin, twc, 
         ASA, PULP, perforation, gender, epigastric_pain, 
         malena, tenderness, degree_perforation, outcome) 

kable_table_pep <- pep %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Peptic Ulcer data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")
print(kable_table_pep)
```


# Get summary statistics
```{r select_data, include false}
# filter() will select males 7+ years old and send
pep %>% 
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    digits = all_continuous() ~ 2) %>% 
  modify_caption("Patient Characteristics (N = {N})") %>%
  as_gt()
```

# Group summary statistics 
```{r um-to-cat, include false}
# THis groups the summary statistics by the outcome variable
tab_outcome <- pep %>% 
  tbl_summary(
    by = outcome,            # this is the grouping variable
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    digits = all_continuous() ~ 2) %>%
  modify_caption("Patient Characteristics and Fatality (N = {N})")

tab_outcome %>%
  as_gt()
```


# Group summary statistics 
```{r um-to-cat, include false}
# THis groups the summary statistics by the gender variable
tab_gender <- pep %>% 
  tbl_summary(
    by = gender,            # this is the grouping variable
    statistic = list(all_continuous() ~ "{mean} ({sd})", 
                     all_categorical() ~ "{n} / {N} ({p}%)"),
    digits = all_continuous() ~ 2) %>%
  modify_caption("Patient Characteristics and Fatality (N = {N})")

tab_outcome %>%
  as_gt()
```


# Now lets merge the two tables
```{r num-to-cat, include false}
# This will merge the previous two tables
tbl_merge(
  tbls = list(tab_gender, tab_outcome),
  tab_spanner = c("**Gender**", "**Outcome**")) %>%
  as_gt()
```

