###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 4
### date: 19/05/2025
###  
###  רגרסיה לינראית
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
library(tidyverse)
library(kableExtra)
library(tibble)
library(readxl)
library(lubridate)
library(haven)
library(gtsummary)
library(ggplot2)
library(ggpubr)
library(GGally)
library(rsq)
library(broom)
library(here)
library(patchwork)
library(plotly)
```

# Get data
```{r load data, include false}
path <- "./Data/coronary.dta"
coronary <- read_dta(path)
```

# Check out the variables
```{r load data, include false}
glimpse(coronary)
print(coronary, n=20)


kable_table_coronary <- coronary %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for Stroke data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_coronary)
```

# Multi-variable regression with lm using three variables
```{r num-to-cat, include false}
# Race is a cat variable so need  
coronary$race <- as.factor(coronary$race)
# Do a simple linear regression (SLR) with chol as the dependent variable 
mlr_chol <- lm(chol ~ dbp + bmi + race, data = coronary)
summary(mlr_chol)

library(gtsummary)
mlr_table <- tbl_regression(
  mlr_chol,
  conf.int = TRUE
) %>%
  modify_caption("**Table: Multiple Linear Regression with Dummy Variables for Race**")

mlr_table
# Looks like dbp and race are significant
```

# Fixed model
```{r num-to-cat, include false}
# Do a  linear regression (LM) with chol as the dependent variable 
mlr_chol_fixed <- lm(chol ~ dbp + race, data = coronary)
summary(mlr_chol_fixed)

library(gtsummary)
mlr_fixed_table <- tbl_regression(
  mlr_chol_fixed,
  conf.int = TRUE
) %>%
  modify_caption("**Table: Multiple Linear Regression with Dummy Variables for Race**")

mlr_fixed_table
# A good model
```


# Interaction (make sure we can interpret each coefficient on its own)
```{r sort_data, include false}
# Use glm to test for interaction
interaction <- lm(chol ~ dbp + race + dbp:race, data = coronary)     #notice the " dbp:race" term
summary(interaction)

interaction_table <- tbl_regression(
  interaction,
  conf.int = TRUE
) %>%
  add_glance_source_note(
    include = c("r.squared", "adj.r.squared")
  )

interaction_table
# There are no significant interactions. Good!
```


# Check residuals (need to be noramly distributed)
```{r sort_data, include false}
# Calculate the residuals
rraw_chol <- resid(mlr_chol_fixed)

# Plot the residuals
  boxplot(rraw_chol)
  
  hist_residuals <- ggplot(data.frame(rraw_chol), aes(x = rraw_chol)) +
    geom_histogram(bins = 10) +
    labs(
      title = "Histogram of Residuals",
      x = "Residuals",
      y = "Count"
    ) +
    theme_minimal()
  hist_residuals

ggplotly(hist_residuals)

  # Boxplot the residuals
  box_residuals <- ggplot(data.frame(rraw_chol), aes(x = rraw_chol)) +
    geom_boxplot() +
    labs(
      title = "Boxplot of Residuals",
      x = "Residuals",
      y = "Count"
    ) +
    theme_minimal()
  box_residuals

ggplotly(box_residuals)
# All looks good.
```


# Scatter plots
```{r sort_data, include false}
# Calculate the residuals
rstd_chol <- rstandard(mlr_chol_sel)  # standardized residuals
pstd_chol <- scale(predict(mlr_chol_sel))  # standardized predicted values
plot(rstd_chol ~ pstd_chol, xlab = "Std predicted", ylab = "Std residuals")
abline(0, 0)  # normal, linear, equal variance

# Plot the residuals
std_plot <- ggplot(data.frame(std_pred = pstd_chol, std_resid = rstd_chol), aes(x = std_pred, y = std_resid)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  labs(title = "Standardized Residuals vs. Standardized Predicted Values",
       x = "Std Predicted",
       y = "Std Residuals") +
  theme_minimal()
std_plot

ggplotly(std_plot)

  # raw residuals and the observed values
plot(rraw_chol ~ coronary$dbp, xlab = "DBP", ylab = "Raw Residuals")
abline(0, 0)

rresid_obs <- ggplot(data.frame(dbp = coronary$dbp, residuals = rraw_chol), aes(x = dbp, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0) +
  labs(title = "Raw Residuals vs. DBP", x = "DBP", y = "Raw Residuals") +
  theme_minimal()
rresid_obs

ggplotly(rresid_obs)
# All looks good.
```