###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 4
### date: 19/05/2025
###  
###  רגרסיה לינראית
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
library(tidyverse)
library(kableExtra)
library(tibble)
library(readxl)
library(lubridate)
library(haven)
library(gtsummary)
library(ggplot2)
library(ggpubr)
library(GGally)
library(rsq)
library(broom)
library(here)
library(patchwork)
library(plotly)
```

# Get data
```{r load data, include false}
path <- "./Data/coronary.dta"
coronary <- read_dta(path)
```


# Fixed model
```{r num-to-cat, include false}
# Do a  linear regression (LM) with chol as the dependent variable 
mlr_chol_fixed <- lm(chol ~ dbp + race, data = coronary)
summary(mlr_chol_fixed)

library(gtsummary)
mlr_fixed_table <- tbl_regression(
  mlr_chol_fixed,
  conf.int = TRUE
) %>%
  modify_caption("**Table: Multiple Linear Regression with Dummy Variables for Race**")

mlr_fixed_table
# A good model
```


# Final model
```{r sort_data, include false}
# Race is a cat variable so need  
coronary$race <- as.factor(coronary$race)
# Use glm to test for interaction
final_model <- lm(chol ~ dbp + race + dbp:race, data = coronary)     #notice the " dbp:race" term
summary(final_model)

model_results <- tbl_regression(
  final_model,
  conf.int = TRUE
) %>%
  add_glance_source_note(
    include = c("r.squared", "adj.r.squared")
  )

model_results
# There are no significant interactions. Good!
```

# Prediction
```{r sort_data, include false}
# Show the predction table
coronary$pred_chol <- predict(final_model)
head(coronary)

#  predicting the cholesterol level for an Indian patient with DBP = 90mmHg
predict(final_model, list(dbp = 90, race = "3"))

#  predicting the cholesterol level for any race patient with DBP = 90mmHg
prections <- data.frame(dbp = c(90, 90, 90), 
                      race = c("1", "2", "3"))
predict(final_model, prections)

# There are no significant interactions. Good!
```

# Now show CIs
```{r sort_data, include false}
prediction_results <- cbind(
  prections,
  predict(final_model, newdata = prections, interval = "confidence")
)
# Round to 3 significant digits
prediction_results$fit <- signif(prediction_results$fit, 3)
prediction_results$lwr <- signif(prediction_results$lwr, 3)
prediction_results$upr <- signif(prediction_results$upr, 3)
# show results
prediction_results

# View nicely formatted table (optional)
library(gt)
gt(prediction_results) %>%
  tab_header(title = "Predicted Cholesterol at DBP = 90 with 95% CI (Rounded)")
```

