###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 4
### date: 19/05/2025
###  
###  רגרסיה לינראית
###

# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

# Load required packages
```{r setup-packages, include false}
library(tidyverse)
library(kableExtra)
library(tibble)
library(readxl)
library(lubridate)
library(haven)
library(gtsummary)
library(ggplot2)
library(ggpubr)
library(GGally)
library(rsq)
library(broom)
library(here)
library(patchwork)
library(plotly)
```

# Get data
```{r load data, include false}
path <- "./Data/fev.txt"
fev <- read_tsv(path)
```

# Check out the variables
```{r load data, include false}
glimpse(fev)
print(fev, n=20)


kable_table_fev <- fev %>%
  slice_head(n = 20) %>%  # Show first 20 rows
  kable("html", align = 'c', caption = "Tibble for fev data (First 20 Rows)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    font_size = 14
  ) %>%
  scroll_box(height = "400px")

# Display in console/viewer (R Markdown or viewer needed for full effect)
print(kable_table_fev)
```

# summary statistics for numerical variables
```{r sort_data, include false}
# Show median and IQR for all numerical variables (5)
fev %>% 
  select(age, fev, height) %>% 
  tbl_summary()
```

# summary statistics for cat variables
```{r sort_data, include false}
# Show percent for all cat variables (5)
fev %>% 
  select(gender, smoking) %>% 
  tbl_summary()
```


# Display pairs
```{r select_data, include false}
# filter() will select males 7+ years old and send
pairs_plot <- fev %>% 
  select(-gender, -smoking) %>% 
  ggpairs()

pairs_plot
ggplotly(pairs_plot)
```

# Multi-variable regression with lm
```{r num-to-cat, include false}
# Do a simple linear regression (SLR) with chol as the dependent variable 
mlr_fev <- lm(fev ~ age + fev + height + gender + smoking, data = fev)
summary(mlr_fev)

tidy(mlr_fev) %>%
  mutate(p.value = case_when(
    p.value < 0.001 ~ "<0.001",
    p.value < 0.01  ~ "<0.01",
    p.value < 0.05  ~ "<0.05",
    TRUE            ~ "≥0.05"
  )) %>%
  kable("html", caption = "Muliple Linear Regression (p-values)") %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "left"
  )
# Assume dbp and race are significant

```

# Run a stepwise analysis
```{r num-to-cat, include false}
# Do a multiple regression (MLR) with chol as the dependent variable 
# both
mlr_chol_stepboth <- step(mlr_chol, direction = "both")

mlr_chol_sel <- lm(chol ~ dbp + bmi + race, data = coronary)
summary(mlr_chol_sel)

model_table_stats <- tbl_regression(mlr_chol_sel,
                             #label = list(dbp = "Diastolic Blood Pressure"),
                             conf.int = TRUE,
                             show_single_row = "dbp",
                             intercept = TRUE) %>%
  modify_header(label = "**coeff**",
                estimate = "**beta**",
                std.error = "**SE**",
                statistic = "**F**",
                p.value = "**p**",
                conf.low = "**CI<sub>95%**") %>%
  modify_table_body(~ .x %>% filter(label != "Abbreviations")) %>%
  add_glance_source_note(
    include = c(r.squared, adj.r.squared, statistic, p.value, logLik, AIC, sigma),
    label = list(
      r.squared = "R²",
      adj.r.squared = "Adj.R²",
      statistic = "F",
      p.value = "p",
      logLik = "log-L",
      sigma = "\U03C3",
      AIC = "AIC"
    )
  ) %>%
  modify_caption("**Table 2: Model Coefficients<br>(fit statistics)**")

model_table_stats
```