###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: סרגרסיה לינארית 05   
### date  : 15/06/2025
###  
### נלמד לעשות רגסיה לינארית
###
### source: https://github.com/drkamarul/multivar_data_analysis/tree/main/data


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```



## Load required packages
```{r load-packages, include false}  
install.packages("pacman")
library(pacman)
pacman::p_load(
  rio,          # File import
  here,         # File locator
  skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics, 
  gtsummary,    # summary statistics and tests
  rstatix,      # statistics
  nortest,      # Anderson-Darling test for normality
  moments,      # skewness and kurtosis
  corrr,        # correlation analayis for numeric variables
  janitor,      # adding totals and percents to tables
  flextable,    # converting tables to HTML
  dplyr,        # For data manipulation
  ggplot2,      # For creating plots
  DescTools,    # For statistical functions like skewness and kurtosis
  car,          # For Levene's test and ANOVA
  vctrs         # For data type handling
            )
```

## Access the data
```{r read-data, echo=FALSE}
## read the data in a file online
file <- "https://github.com/drkamarul/multivar_data_analysis/blob/main/data/coronary.dta"
df2 <- import(file, trust  = TRUE)
summary(df2)
glimpse(df2)
```

```{r setup, include=FALSE}
data<-birthsR 



###pearson
test <- cor.test(data$weight0, data$hemoglobin_0, method = "pearson", use = "complete.obs")
test




##linear
model <- lm(hemoglobin_0 ~ weight0, data = data)

summary_model <- summary(model)

summary_model


```

##question 2
```{r cars}



model2 <- lm(weight1 ~ newborn_gender, data = data)

summary_model2 <- summary(model2)

summary_model2



```

##question 3
```{r cars}

install.packages("lm.beta")
library(lm.beta)


###colinearity test

test2 <- cor.test(data$height4,  data$newborn_gender , method = "spearman", use = "complete.obs")
test3 <- cor.test(data$height4,  data$mother_weight , method = "spearman", use = "complete.obs")
test4 <- cor.test(data$mother_weight,  data$newborn_gender , method = "spearman", use = "complete.obs")
test2
test3
test4
```