###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: סרגרסיה לינארית 05   
### date  : 15/06/2025
###  
###  מלמד לעשות רגסיה מרובה
###


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

##question 3
```{r cars}

install.packages("lm.beta")
library(lm.beta)


###colinearity test

test2 <- cor.test(data$height4,  data$newborn_gender , method = "spearman", use = "complete.obs")
test3 <- cor.test(data$height4,  data$mother_weight , method = "spearman", use = "complete.obs")
test4 <- cor.test(data$mother_weight,  data$newborn_gender , method = "spearman", use = "complete.obs")
test2
test3
test4


##linear model
model3 <- lm(weight4 ~ height4 + newborn_gender + mother_weight, data = data)

summary_model3 <- summary(model3)


print(summary_model3)

# Calculate the standardized beta coefficients
model_beta3 <- lm.beta(model3)
model_beta3

```
