###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: רגרסיה אורדינלית 06   
### date  : 19/06/2025
###  
###  מלמד לעשות רגרסיה לוגיסטי מרובה על משתנים אורדינליים
### 
### https://www.scielosp.org/pdf/rsp/2009.v43n1/183-194/en


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

## Load required packages
```{r load-packages, include false}  
options("install.lock"=FALSE)
install.packages("pacman")
library(pacman)
pacman::p_load(
  rio,          # File import
  here,         # File locator
  skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics, 
  gtsummary,    # summary statistics and tests
  rstatix,      # statistics
  nortest,      # Anderson-Darling test for normality
  moments,      # skewness and kurtosis
  corrr,        # correlation analayis for numeric variables
  janitor,      # adding totals and percents to tables
  flextable,    # converting tables to HTML
  dplyr,        # For data manipulation
  ggplot2,      # For creating plots
  DescTools,    # For statistical functions like skewness and kurtosis
  car,          # For Levene's test and ANOVA
  vctrs,        # For data type handling
  reshape2,     # For reshaping data
  MASS          # For statistical functions (polr for ordinal regression)
            )
```

## Access the data
```{r read-data, echo=FALSE}
## read the data in a file online
# file <- "coronary.dta"     # use this if the file is on your computer
file <- "https://raw.githubusercontent.com/drkamarul/multivar_data_analysis/refs/heads/main/data/peptic_ulcer.xlsx"
df4 <- import(file, trust  = TRUE)
summary(df4)
glimpse(df4)
```

## Fix the data
```{r fix-data, echo=FALSE}
# Make sure degree_perforation is an ordered factor
df$degree_perforation <- factor(df$degree_perforation, 
                                levels = c("mild", "moderate", "severe"), 
                                ordered = TRUE)
                               
```

## Perfrom an ordinal linear regression
```{r rord-regression, echo=FALSE}
# Mutate DEATH_EVENT to factor
df4 <- df %>%
  mutate(degree_perforation = as.factor(degree_perforation))

## Ordinal Regression Model
ord_lr <- polr(degree_perforation ~ PULP + hemoglobin + systolic , data = df4, Hess = TRUE)
summary(ord_lr)





# Get coefficients and standard errors
(ctable <- coef(summary(model)))

# Calculate p-values
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2

# Combine with coefficients
(ctable <- cbind(ctable, "p value" = p))

# Confidence intervals
ci <- confint(model)
exp(cbind(OR = coef(model), ci))







# Predict for new data
newdata <- data.frame(age = 45, smoking = "yes", alcohol = "no")
predict(model, newdata, type = "probs")





odr_lr_summary <- tbl_regression(
  ofr_lr,
  intercept = TRUE,
  estimate_fun = ~round(.x, 2)
) %>%
  add_glance_table(
    include = c(r.squared, adj.r.squared, AIC, p.value)
  )
ofr_lr_summary
```



## Show ordinal linear regression summary table
```{r pearson, include=FALSE}
ord_lr_summary <- tbl_regression(ord_lr,
                             #label = list(dbp = "Diastolic Blood Pressure"),
                             conf.int = TRUE,
                             show_single_row = "DEATH_EVENT",
                             intercept = TRUE) %>%
  modify_header(label = "**coeff**",
                estimate = "**beta**",
                std.error = "**SE**",
                statistic = "**F**",
                p.value = "**p**",
                conf.low = "**CI<sub>95%**") %>%
  #modify_table_body(~ .x %>% filter(label != "Abbreviations")) %>%
  add_glance_source_note(
    include = c(r.squared,
                adj.r.squared,
                statistic,
                p.value,
                #logLik,
                AIC
                #sigma
                ),
    label = list(
      r.squared = "R²",
      adj.r.squared = "Adj.R²",
      statistic = "F",
      p.value = "p",
      logLik = "log-L",
      sigma = "\U03C3",
      AIC = "AIC"
    )
  ) %>%
  modify_caption("**Table 2: Model Coefficients<br>(fit statistics)**")

odr_lr_summary
```
