###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: רגרסיה אורדינלית מרובה 07   
### date  : 15/06/2025
###  
###  מלמד לעשות רגרסיה לוגיסטי מרובה על משתנים אורדינליים
###


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

```{r setup, include=FALSE}
# 0. טעינת חבילות נדרשות
install.packages(c("tidyverse", "nnet", "MASS", "VGAM")) 
library(tidyverse)
library(nnet)   # לרגרסיה מולטינומיאלית
library(MASS)   # רגרסיה אורדינלית
library(VGAM)   # אופציה נוספת לאורדינלית אם רוצים
library(readxl) # לקריאת קבצי Excel


data <- read_excel("C:/תרגולים/HIT/epi1/HeartDiseaseData.xls")

data$ClinicType <- factor(data$ClinicType, 
                           levels = c(1, 2, 3, 4), 
                           labels = c("City", "Kibutz", "Moshav", "other"))
data$SexCode <- factor(data$SexCode, levels = c(0,1), labels = c("female", "male"))
data$LDL_ordinal <- factor(data$LDL_ordinal, ordered = TRUE, levels = c(0,1,2))
data$StatusCodeLast <- factor(data$StatusCodeLast, levels = c(1,2,3,4),
                              labels = c("no test is made", "normal", "one isn't normal", "not normal"))


#1 בניית המודל
model1 <- glm(DisIHD ~ ClinicType + Age, data = data, family = binomial)

summary(model1)

# exp(coef(model1)) 
exp(confint(model1))
exp(coef(model1))



```


```{r setup, include=FALSE}


# מודל אורדינלי
model2 <- polr(LDL_ordinal ~ Age + SexCode +HDL0, data = data, Hess = TRUE)

# סיכום התוצאות
summary(model2)

# חישוב ערכי p
(ctable <- coef(summary(model2)))
p_values <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
(ctable <- cbind(ctable, "p value" = p_values))
OR2 <- exp(coef(model2))  # Odds Ratios
CI2 <- exp(confint(model2))  # Confidence Intervals
OR2
CI2
```

```{r setup, include=FALSE}
###ביקורת תמיד  הערך הנמוך ביותר אך ניתן לשנות
data$StatusCodeLast <- relevel(data$StatusCodeLast, ref = "not normal")

# מודל מולטינומיאלי
model3 <- multinom(StatusCodeLast ~ DisIHD + Age + SexCode + DisCVA, data = data)


# סיכום התוצאות
summary(model3)

# OR P VALUE AND CI
             
                
z <- summary(model3)$coefficients / summary(model3)$standard.errors
p_values3 <- (1 - pnorm(abs(z), 0, 1)) * 2
OR3 <- exp(coef(model3))
se3 <- summary(model3)$standard.errors
z_crit <- 1.96  # 95% רווח סמך
CI_low3 <- exp(coef(model3) - z_crit * se3)
CI_high3 <- exp(coef(model3) + z_crit * se3)

result_tables <- list()

for (i in 1:nrow(OR3)) {
  result_tables[[rownames(OR3)[i]]] <- data.frame(
    Predictor = colnames(OR3),
    OR = round(OR3[i,], 3),
    CI_low = round(CI_low3[i,], 3),
    CI_high = round(CI_high3[i,], 3),
    p_value = round(p_values3[i,], 4)
  )
}

# הצגה של הטבלאות
result_tables          
                
```

