###
### name  :  ר
### ID    : [ספר תעת ת]
### course: פ (HIT.ac.il)
### lesson: ס ס 07  RR 
### date  : 03/07/2025
###  
###  quasi ררסת פס  
###
### source:  https://bookdown.org/drki_musa/dataanalysis/poisson-regression.html
###          https://github.com/drkamarul/multivar_data_analysis/tree/main/data


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
dev.off()
```

## Load required packages
```{r load-packages, include false}
options("install.lock"=FALSE)
if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(
  rio,                    # File import
  tidyverse,              # data management + ggplot2 graphics,
  broom,                  # For tidying model outputs
  dplyr,                  # For data manipulation
  gt,                     # Nice beuatiful tables
  nortest,                # Anderson-Darling test for normality
  ggplot2,                # For creating plots
  DescTools,              # For statistical functions like skewness and kurtosis
  psych,                  # to get a table of all summary statistics
  janitor,                # adding totals and percents to tables
  car,                    # For Levene's test and ANOVA
  gtsummary,              # summary statistics and tests
  corrr,                  # correlation
  lmtest,                 # linear regression tets
  parameters,             # calculate standardized parameters/coefficients
  GGally,                 # to make a correlation matrix
  skimr,                  # get overview of data
  pROC,                   # For ROC analysis
  performance,            # For model performance metrics
  MASS,                   # For statistical functions (polr for ordinal regression)ordinal
  caret,                  # For confusion matrix and classification metrics
  ggeffects,              # To display the confusion matrix
  ResourceSelection,      # For Hosmer-Lemeshow test for goodness of fit 
  ordinal,                # For ordinal regression statistical functions 
  VGAM,                   # for multinomial logistic regression
  epiDisplay,             # For epi data type handling    
            )
# Install/load flexplot
if (!require("devtools")) devtools::install_github("dustinfife/flexplot", ref = "development")  ;  if (!require("pacman")) install.packages("pacman")  ;  library(flexplot)
```

## Access the data
```{r read-data, echo=FALSE}
## read the data in a file online
# file <- "./EpiData/asthma.csv"     #  use this if the file is on your computer
file <- "https://raw.githubusercontent.com/drkamarul/multivar_data_analysis/refs/heads/main/data/asthma.csv"
df6 <- import(file, trust  = TRUE)
summary(df6)
glimpse(df6)  # get an overview of the data
```

## Do summary stats
```{r read-data, echo=FALSE}
## read the data in a file online
epiDisplay::codebook(df6)
```

## A simple Poisson regression univariate analysis
```{r read-data, echo=FALSE}
## read the data in a file online
qpr <- glm(attack ~ ., data = df6, family = "quasipoisson")
tidy(qpr, conf.int = TRUE)
```





### -------------------------------------------------




### שת תר עצ

## ש 1
```{r question-1, echo = TRUE}
# 

```

## ש 2
```{r question-2, echo = TRUE}
# 

```

## ש 3
```{r question-3, echo = TRUE}
# 

```