###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: סיכון יחסי 07  RR 
### date  : 15/06/2025
###  
###  נלמד לבצע ניתוח סיכון יחסי
###


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

```{r setup, include=FALSE}
# 0. טעינת חבילות נדרשות
install.packages(c("tidyverse", "nnet", "MASS", "VGAM")) 
library(tidyverse)
library(readxl) # לקריאת קבצי Excel
data <- read_excel("C:/תרגולים/HIT/epi1/cohort.xls") 

###question 1

# Create 2x2 table

df <- na.omit(data[, c("DisObes", "stroke")])

# Now compute the table
tab <- table(df$DisObes, df$stroke)


# Assign cells
a <- tab[1,1]  # Not obese, no stroke
b <- tab[1,2]  # Not obese, stroke
c <- tab[2,1]  # Obese, no stroke
d <- tab[2,2]  # Obese, stroke

# Calculate risks
risk_obese <- d / (c + d)
risk_not_obese <- b / (a + b)

# Relative Risk
RR <- risk_obese / risk_not_obese
# Standard error of log(RR)
se_log_rr <- sqrt( (1/b) - (1/(a + b)) + (1/d) - (1/(c + d)) )

# Z for 95% CI
z <- qnorm(0.975)

# Confidence Interval (log scale)
log_rr <- log(RR)
ci_lower <- exp(log_rr - z * se_log_rr)
ci_upper <- exp(log_rr + z * se_log_rr)
z_stat <- log_rr / se_log_rr
p_value <- 2 * (1 - pnorm(abs(z_stat)))

RR
ci_lower
ci_upper
p_value



```



###question 2
```{r setup, include=FALSE}
death_freq <- table(data$Death)
death_percent <- prop.table(death_freq) * 100

death_percent

df <- na.omit(data[, c("Death", "stroke", "SexCode", "DisObes", "DisSmok", "DisDM")])


model1 <- glm(Death ~ SexCode + DisSmok , data = df, family = binomial())

OR<-exp(coef(model1))


model2 <- glm(Death ~ SexCode + DisSmok , data = df, family = poisson())

RR <- exp(coef(model2))

OR
RR


####stroke

stroke_freq <- table(data$stroke)
stroke_percent <- prop.table(stroke_freq) * 100

stroke_percent



model1 <- glm(stroke~ SexCode + DisSmok , data = df, family = binomial())

OR<-exp(coef(model1))


model2 <- glm(stroke ~ SexCode + DisSmok , data = df, family = poisson())

RR <- exp(coef(model2))

OR
RR



```
####question 3
```{r setup, include=FALSE}
# Load required packages
install.packages("sandwich")
install.packages("lmtest")
library(sandwich)
library(lmtest)

# Clean data
df <- na.omit(data[, c("stroke", "SexCode", "DisObes", "DisSmok", "DisDM")])

# Fit Poisson model
model <- glm(stroke ~ SexCode + DisObes + DisSmok + DisDM, data = df, family = poisson())

# Get robust standard errors
robust_se <- sqrt(diag(vcovHC(model, type = "HC0")))
coeftest(model, vcov. = vcovHC(model, type = "HC0"))
# Calculate RR and 95% CI
RR <- exp(coef(model))
CI_lower <- exp(coef(model) - 1.96 * robust_se)
CI_upper <- exp(coef(model) + 1.96 * robust_se)

RR
CI_lower
CI_upper


# Deviance and Pearson chi-square
deviance <- deviance(model)
df_resid <- df.residual(model)

pearson <- sum(residuals(model, type = "pearson")^2)

cat("Deviance =", deviance, "on", df_resid, "df\n")
cat("Pearson Chi-square =", pearson, "on", df_resid, "df\n")
```



###id deviance/df>1.5 than:
# Fit quasi-Poisson model
```{r setup, include=FALSE}

model_qp <- glm(stroke ~ SexCode + DisObes + DisSmok + DisDM, data = df, family = quasipoisson())

# Coefficients
coefs <- coef(model_qp)

# Standard errors (already adjusted for dispersion)
se_qp <- summary(model_qp)$coefficients[, "Std. Error"]

# RR (exponentiated coefficients)
RR <- exp(coefs)

# 95% CI using Wald method
CI_lower <- exp(coefs - 1.96 * se_qp)
CI_upper <- exp(coefs + 1.96 * se_qp)

  RR = RR
  CI_lower
  CI_upper
 



```


