###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 09 רגרסיית קוקס   Cox regression
### date  : 15/06/2025
###  
###  נלמד לבצע רגרסיית קוקס
###


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```

```{r setup, include=FALSE}
library(dplyr)       
library(ggplot2)  
library(readxl)
library(epitools)


data<-read_excel("C:/תרגולים/bios2_R/קבצים/CHF_for COX.xls")

```


```{r, include=FALSE}

mean_survival_time <- mean(data$survival_time, na.rm = TRUE)
median_survival_time <- median(data$survival_time, na.rm = TRUE)


mean_survival_time
median_survival_time

```


```{r,include=FALSE}

library(survival)
library(survminer)


surv_object <- Surv(time = data$survival_time, event = data$Death)
fit <- survfit(surv_object ~ 1)
fit_summary <- summary(fit)

#creating life table
km_data <- data.frame(
  time = fit_summary$time,
  n_risk = fit_summary$n.risk,
  n_event = fit_summary$n.event,
  survival = fit_summary$surv,
  std_error = fit_summary$std.err
)



print(km_data)
```



```{r,include=FALSE}

surv_object <- Surv(time = data$survival_time, event = data$Death)
fit <- survfit(surv_object ~ FamilyStatus, data = data)

#Kaplan-Meier survival curves with p value
ggsurvplot(fit, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
           title = "Kaplan-Meier Survival Curve by FamilyStatus",
           legend.title = "Family Status",
           legend.labs = levels(data$FamilyStatus),
           pval = TRUE)


```

```{r,include=FALSE}
###first of all we check proportion assumption


surv_object <- Surv(time = data$survival_time, event = data$Death)
fit_ch<- survfit(surv_object ~ Charlson_gr, data = data)


ggsurvplot(fit_ch, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
          pval = FALSE)


fit_age <- survfit(surv_object ~ Age65, data = data)
ggsurvplot(fit_age, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
          pval = FALSE)


```

```{r,include=FALSE}

###we should enter charlson_gr as dummy
data$Charlson_gr <- as.factor(data$Charlson_gr)

cox_model <- coxph(Surv(survival_time, Death) ~ FamilyStatus + Age65 + Charlson_gr, data = data)

# Summary of the Cox model
cox_summary <- summary(cox_model)

# -2 log-likelihood for null model
log_likelihood_null<- cox_model$loglik[1]
neg2_log_likelihood_null <- -2 * log_likelihood_null

#-2 log-likelihood for fitted model
log_likelihood <- cox_model$loglik[2]
neg2_log_likelihood <- -2 * log_likelihood



cox_summary
neg2_log_likelihood
neg2_log_likelihood_null


#### proportional hazard assumption test, if p<0.05 the assumption is violated, also if the line isnwt horizontal(!!) around 0, the assumption violated 

schoenfeld_test<-cox.zph(cox_model)

schoenfeld_test

plot(schoenfeld_test)

```
