###
### name: דוד בורג
### ID  : [מספר תעודת זהות]
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 09 רגרסיית קוקס   Cox regression
### date  : 15/06/2025
###  
###  Cox נלמד לבצע רגרסיית 
###
### source:  https://bookdown.org/drki_musa/dataanalysis/survival-analysis-kaplan-meier-and-cox-proportional-hazard-ph-regression.html#semi-parametric-models-in-survival-analysis


## Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
dev.off()
```

## Load required packages
```{r load-packages, include false}
options("install.lock"=FALSE)
if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(
  rio,          # File import
  tidyverse,    # data management + ggplot2 graphics, 
  gt,           # Nice beuatiful tables
  nortest,      # Anderson-Darling test for normality
  ggplot2,      # For creating plots
  DescTools,    # For statistical functions like skewness and kurtosis
  janitor,      # adding totals and percents to tables
  car,           # For Levene's test and ANOVA
  gtsummary,    # summary statistics and tests
  corrr,        # correlation analayis for numeric variables
  dplyr,        # For data manipulation
  reshape2,     # For reshaping data
  skimr,        # get overview of data
  performance,           # For model performance metrics
  ResourceSelection,     # For goodness of fit tests
  broom,                 # For tidying model outputs
  pROC,                  # For ROC analysis
  caret,
  MASS,          # For statistical functions (polr for ordinal regression)
  epiDisplay,    # 
  survival,
  survminer
            )
```

## Access the data
```{r read-data, echo=FALSE}
## read the data in a file online
# file <- "./EpiData/stroke_data.csv"     # use this if the file is on your computer
file <- "https://raw.githubusercontent.com/drkamarul/multivar_data_analysis/refs/heads/main/data/stroke_data.csv"
df6 <- import(file, trust  = TRUE)
summary(df6)
glimpse(df6)
```

## Do a simple Cox
```{r read-data, echo=FALSE}
#
cox_reg_1 <- 
  coxph(Surv(time = time2, 
             event = status == 'dead') ~ stroke_type,
                     data = df6)

summary(cox_reg_1)

# Crude log hazard (HR)
tidy(cox_reg_1,
     conf.int = TRUE)


# Hazard ratio (HR)
tidy(cox_reg_1, 
     exponentiate = TRUE,
     conf.int = TRUE)
```

## Do another simple Cox
```{r read-data, echo=FALSE}
#
cox_reg_2 <- 
  coxph(Surv(time = time2, 
             event = status == 'dead') ~ gcs,
                     data = df6)

summary(cox_reg_2)

# Crude log hazard (HR)
tidy(cox_reg_2,
     conf.int = TRUE)


# Hazard ratio (HR)
tidy(cox_reg_2, 
     exponentiate = TRUE,
     conf.int = TRUE)
```

## Do a model on all coviarates
```{r read-data, echo=FALSE}
#
df6 %>%
  dplyr::select(time2, status, sex, dm, gcs, sbp, dbp, wbc, 
                stroke_type, referral_from) %>%
  tbl_uvregression(
    method = coxph,
    y = Surv(time2, event = status == 'dead'),
    exponentiate = TRUE,
    pvalue_fun = ~style_pvalue(.x, digits = 3)
  ) %>%
  as_gt()
```














```{r setup, include=FALSE}
library(dplyr)       
library(ggplot2)  
library(readxl)
library(epitools)


data<-read_excel("C:/תרגולים/bios2_R/קבצים/CHF_for COX.xls")

```


```{r, include=FALSE}

mean_survival_time <- mean(data$survival_time, na.rm = TRUE)
median_survival_time <- median(data$survival_time, na.rm = TRUE)


mean_survival_time
median_survival_time

```


```{r,include=FALSE}

library(survival)
library(survminer)


surv_object <- Surv(time = data$survival_time, event = data$Death)
fit <- survfit(surv_object ~ 1)
fit_summary <- summary(fit)

#creating life table
km_data <- data.frame(
  time = fit_summary$time,
  n_risk = fit_summary$n.risk,
  n_event = fit_summary$n.event,
  survival = fit_summary$surv,
  std_error = fit_summary$std.err
)



print(km_data)
```



```{r,include=FALSE}

surv_object <- Surv(time = data$survival_time, event = data$Death)
fit <- survfit(surv_object ~ FamilyStatus, data = data)

#Kaplan-Meier survival curves with p value
ggsurvplot(fit, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
           title = "Kaplan-Meier Survival Curve by FamilyStatus",
           legend.title = "Family Status",
           legend.labs = levels(data$FamilyStatus),
           pval = TRUE)


```

```{r,include=FALSE}
###first of all we check proportion assumption


surv_object <- Surv(time = data$survival_time, event = data$Death)
fit_ch<- survfit(surv_object ~ Charlson_gr, data = data)


ggsurvplot(fit_ch, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
          pval = FALSE)


fit_age <- survfit(surv_object ~ Age65, data = data)
ggsurvplot(fit_age, data = data, risk.table = TRUE, 
           ggtheme = theme_minimal(),
           xlab = "Time",
           ylab = "Survival Probability",
          pval = FALSE)


```

```{r,include=FALSE}

###we should enter charlson_gr as dummy
data$Charlson_gr <- as.factor(data$Charlson_gr)

cox_model <- coxph(Surv(survival_time, Death) ~ FamilyStatus + Age65 + Charlson_gr, data = data)

# Summary of the Cox model
cox_summary <- summary(cox_model)

# -2 log-likelihood for null model
log_likelihood_null<- cox_model$loglik[1]
neg2_log_likelihood_null <- -2 * log_likelihood_null

#-2 log-likelihood for fitted model
log_likelihood <- cox_model$loglik[2]
neg2_log_likelihood <- -2 * log_likelihood



cox_summary
neg2_log_likelihood
neg2_log_likelihood_null


#### proportional hazard assumption test, if p<0.05 the assumption is violated, also if the line isnwt horizontal(!!) around 0, the assumption violated 

schoenfeld_test<-cox.zph(cox_model)

schoenfeld_test

plot(schoenfeld_test)

```
