###
### name: דוד בורג
### course: אפידמיולוגיה (HIT.ac.il)
### lesson: 0   
### date: 01/07/2025
###  
###  זה קוד שיוריד את כל החבילות והקבצים שנצטרך בקורס הזה


# Reset memory
```{r setup-packages, include false}
rm(list = ls(all.names = TRUE))
lapply(paste('package:',names(sessionInfo()$otherPkgs),sep=""),detach,character.only=TRUE,unload=TRUE,force=TRUE)
gc()
```


### ------------------------------------------------


## Install required packages
```{r load-packages, include false}  
options("install.lock"=FALSE)
if (!require("pacman")) install.packages("pacman")
library(pacman)
pacman::p_load(
  rmarkdown,
  remotes,
  rio,          # File import
  Here,         # File locator
  tidyverse,    # data management + ggplot2 graphics, 
  gt,           # Nice beuatiful tables
  nortest,      # Anderson-Darling test for normality
  ggplot2,      # For creating plots
  DescTools,    # For statistical functions like skewness and kurtosis
  janitor,      # adding totals and percents to tables
  car,           # For Levene's test and ANOVA
  gtsummary,    # summary statistics and tests
  corrr,        # correlation analayis for numeric variables
  dplyr,        # For data manipulation
  reshape2,     # For reshaping data
  skimr,        # get overview of data
  performance,           # For model performance metrics
  ResourceSelection,     # For goodness of fit tests
  broom,                 # For tidying model outputs
  pROC,                  # For ROC analysis
  caret,
  MASS                   # For statistical functions (polr for ordinal regression)
  epiDisplay             # For data type handling
  rstatix,               # statistics
  flextable,             # converting tables to HTML
  vctrs                 # For data type handling
            )


# This will install the LogisticDx package from the archive
# Note: The package is not be available on CRAN anymore, so
# the URL is used
install.packages(c('rms', 'statmod', 'speedglm', 'pROC', 'aod'))
install.packages(
  "https://cran.r-project.org/src/contrib/Archive/LogisticDx/LogisticDx_0.3.tar.gz",
dependencies = TRUE
)

install.packages('httpgd', repos = c('https://community.r-multiverse.org', 'https://cloud.r-project.org'))
install.packages("vscDebugger", repos = "https://manuelhentschel.r-universe.dev")


```


### ------------------------------------------------


## Download code examples for Course
```{r download-data, include false}
# Install and load gh package if not already installed
if (!require("gh", quietly = TRUE)) install.packages("gh", dependencies = TRUE); library(gh)

# Get list of files from the specified folder
files <- gh("GET /repos/:owner/:repo/contents/:path",
            owner = "Model-Lab-Net",
            repo = "Courses",
            path = "Epi/Code")
# sapply(files, function(x) x$name)         # Extract file names

# Download the files
target_dir <- "./EpiCode"              # Define the target folder

if (!dir.exists(target_dir)) {        # Create folder if it doesn't exist
    dir.create(target_dir)}

for (file in files)                   # Download the files in a loop
       {dest_path <- file.path(target_dir, file$name)
        download.file(file$download_url, destfile = dest_path)
       }
```


### ------------------------------------------------


## Download datafiles for examples in Course
```{r download-data, include false}
# Install and load gh package if not already installed
if (!require("gh", quietly = TRUE)) install.packages("gh", dependencies = TRUE); library(gh)

# Get list of files from the specified folder
files <- gh("GET /repos/:owner/:repo/contents/:path",
            owner = "Model-Lab-Net",
            repo = "Courses",
            path = "Epi/Data")
# sapply(files, function(x) x$name)         # Extract file names

# Download the files
target_dir <- "./EpiData"              # Define the target folder

if (!dir.exists(target_dir)) {          # Create folder if it doesn't exist
    dir.create(target_dir)}

for (file in files)                     # Download the files in a loop
       {dest_path <- file.path(target_dir, file$name)
        download.file(file$download_url, destfile = dest_path)
       }

```



### ------------------------------------------------


# Download datafiles for HW (just in case)
```{r download-data, include false}
download.file("https://raw.githubusercontent.com/GTPB/PSLS20/master/data/fev.txt", destfile = "./EpiCode/HWdata_1.txt")
download.file("https://raw.githubusercontent.com/ThecoderPinar/Diabetes_Health_Prediction_and_Analysis/refs/heads/main/raw/diabetes_data.csv", destfile = "./EpiCode/HWdata_2.csv")
download.file("https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/refs/heads/master/csv/survival/cancer.csv", destfile = "./EpiCode/HWdata_3.csv")
```


### ------------------------------------------------


# Download exercise data files (just in case)
```{r download-data, include false}
# Install and load gh package if not already installed
if (!require("gh", quietly = TRUE)) install.packages("gh", dependencies = TRUE); library(gh)

# Get list of files from the specified folder
files <- gh("GET /repos/:owner/:repo/contents/:path",
            owner = "drkamarul",
            repo = "multivar_data_analysis",
            path = "data")
# sapply(files, function(x) x$name)         # Get file names

# Download the files
target_dir <- "./EpiData"                  # Define the target folder

if (!dir.exists(target_dir)) {              # Create folder if it doesn't exist
    dir.create(target_dir)}

for (file in files)                         # Download the files in a loop
       {dest_path <- file.path(target_dir, file$name)
        download.file(file$download_url, destfile = dest_path)
       }


# Download some more files for Course
files_misc <- c("https://raw.githubusercontent.com/appliedepi/epiRhandbook_eng/refs/heads/master/data/linelist_cleaned.rds"
                ,"https://raw.githubusercontent.com/zabore/mmedr/refs/heads/main/data/breastcancer.csv"
                ,"https://raw.githubusercontent.com/ThecoderPinar/Diabetes_Health_Prediction_and_Analysis/refs/heads/main/raw/diabetes_data.csv"
#               ,
#               ,
#               ,
#               ,
#               ,
#               ,
#               ,
              )

for (url in files_misc) {
     destfile <- file.path(target_dir, basename(url))
     download.file(url, destfile)
    }
```
